name: "Docker Build"
description: "Build Docker image"
inputs:
  docker-build-path:
    description: "Path to the source code for Docker build"
    required: false
    default: "."
  image-name:
    description: "Name of the Docker image"
    required: false
  appid:
    description: "Application ID"
    required: false
    default: "0"
  orgid:
    description: "Organization ID"
    required: false
    default: "0"
  buid:
    description: "Business Unit ID"
    required: false
  tag-override:
    description: "Force specific tag/version"
    required: false
  build-image:
    description: "Whether to build the image (true/false)"
    required: false
    default: "true"
outputs:
  docker-tags:
    description: "All generated tags, comma-separated"
    value: ${{ steps.tag.outputs.docker-tags }}
  safe-branch:
    description: "The sanitized branch name used in tag"
    value: ${{ steps.tag.outputs.safe-branch }}

runs:
  using: "composite"
  steps:
    - name: Docker Tag
      id: tag
      shell: bash
      env:
        IMAGE_NAME: ${{ inputs.image-name }}
        APPID: ${{ inputs.appid }}
        ORGID: ${{ inputs.orgid }}
        BUID: ${{ inputs.buid }}
        TAG_OVERRIDE: ${{ inputs.tag-override }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      run: bash ${{ github.action_path }}/scripts/calculate-tag.sh

    - name: Docker Build
      if: inputs.build-image == 'true'
      run: |
        if [ "${{ env.IS_MAIN }}" == "true" ]; then
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} -t ${{ env.IMAGE_NAME }}:latest ${{ inputs.docker-build-path }}
        else
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} ${{ inputs.docker-build-path }}
        fi
      shell: bash

    - name: Docker Scan
      if: inputs.build-image == 'true'
      uses: orbitcluster/oc-cicd-docker-scan-workflow@v1
      with:
        image-name: ${{ env.IMAGE_NAME }}
        image-tag: ${{ env.DOCKER_TAG }}
